version: '3'
services:
  cache-redis-production:
    image: redis:6.2-alpine
    container_name: chat_redis_prod
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass UI78F8o67sd8o6df907IA589o67er8op6D
    volumes: 
      - cache:/data

  postgres-service-production:
    image: postgres:latest
    container_name: chat_postgres_prod
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_DB: Dev_Messages
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 67F68ftg8IOFGuvyUFG
    volumes:
      - ./var/lib/postgres:/var/lib/postgres
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d

volumes:
  cache:
    driver: local

networks:
  default:
    external:
      name: gol_golang_network